### ISSUE TITLE
Agent doesn't work with 5th version of RP

### ISSUE THREAD

**Issue by slavamarkovski** [reportportal/agent-js-jasmine#24]
Jasmine agent throws the following error for the 5th version of Report Portal:
Error: Request failed with status code 400: {"errorCode":4001,"message":"Incorrect Request. [Value is not allowed for field 'status'.] "}
    at axios.then.catch (node_modules\reportportal-client\lib\rest.js:27:23)

**Comment by KatsiarynaTatarynovich** [comment]
This issue was fixed for 5th version of RP

**Comment by slavamarkovski** [comment]
Hello @KatsiarynaTatarynovich, can you please advise when can we expect this fix released?
Also I can apply the fix in my project until official release but I don't see any commits here..
Thanks.

**Comment by greyarch** [comment]
Hi, I am running the latest version of the docker images and still get that error. Is this a case of not updating the docker images?

**Comment by KatsiarynaTatarynovich** [comment]
Hello @slavamarkovski this error appears due to the Client issue. This issue has already fixed. You can expect this fix released during the next week.
If you want to apply the fix in your project before release, you should specify a branch for an npm package in dependencies of agent-js-jasmine
- replace **version** of **reportportal-client** with `git://github.com/reportportal/client-javascript.git#EPMRPP-45141`
